spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oa_dev?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 关闭所有 SQL 初始化与依赖分析
  sql:
    init:
      mode: never

server:
  port: 8080

management:
  metrics:
    enable:
      rabbit: false
  health:
    rabbit:
      enabled: false
    redis:
      enabled: false
    db:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN
    org.springframework.amqp: WARN
    org.springframework.data.redis: WARN
    com.baomidou.mybatisplus: WARN
    com.company.oa: INFO