components:
  schemas:
    SysUserDTO:
      type: object
      properties:
        username: {type: string}
        password: {type: string}
        realName: {type: string}
        email: {type: string}
        mobile: {type: string}
        status: {type: integer}
        deptId: {type: integer}
    SysUserVO:
      type: object
      properties:
        id: {type: integer, format: int64}
        username: {type: string}
        realName: {type: string}
        email: {type: string}
        mobile: {type: string}
        status: {type: integer}
        deptName: {type: string}
        createTime: {type: string, format: date-time}

paths:
  /api/users:
    get:
      summary: 获取用户列表（分页）
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
    post:
      summary: 新增用户
  /api/users/{id}:
    get:
      summary: 获取单个用户
    put:
      summary: 更新用户
    delete:
      summary: 删除用户
components:
  schemas:
    SysDeptDTO:
      type: object
      required: [name]
      properties:
        name: {type: string}
        parentId: {type: integer, format: int64}
        orderNum: {type: integer}
        status: {type: integer}
    SysDeptVO:
      type: object
      properties:
        id: {type: integer, format: int64}
        name: {type: string}
        parentId: {type: integer, format: int64}
        orderNum: {type: integer}
        status: {type: integer}
        createTime: {type: string, format: date-time}
        updateTime: {type: string, format: date-time}

paths:
  /api/depts:
    get:
      summary: 分页获取部门列表
      parameters:
        - name: page; in: query; schema: {type: integer}; required: false
        - name: size; in: query; schema: {type: integer}; required: false
      responses:
        "200": {description: OK}
    post:
      summary: 新增部门
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SysDeptDTO' }
      responses:
        "200": {description: OK}
  /api/depts/{id}:
    get:
      summary: 根据 ID 查询部门
      parameters:
        - name: id; in: path; schema: {type: integer, format: int64}; required: true
      responses:
        "200": {description: OK}
    put:
      summary: 更新部门
      parameters:
        - name: id; in: path; required: true; schema: {type: integer}
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SysDeptDTO' }
      responses:
        "200": {description: OK}
    delete:
      summary: 删除部门
      parameters:
        - name: id; in: path; schema: {type: integer}; required: true
      responses:
        "200": {description: OK}
components:
  schemas:
    SysPostDTO:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
        code:
          type: string
        description:
          type: string
        status:
          type: integer
    SysPostVO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
        description:
          type: string
        status:
          type: integer
        createTime:
          type: string
          format: date-time
        updateTime:
          type: string
          format: date-time

paths:
  /api/posts:
    get:
      summary: 分页查询岗位
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: size
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: OK
    post:
      summary: 新增岗位
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SysPostDTO'
      responses:
        "200":
          description: OK
  /api/posts/{id}:
    get:
      summary: 根据 ID 查询岗位
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
    put:
      summary: 更新岗位
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SysPostDTO'
      responses:
        "200":
          description: OK
    delete:
      summary: 删除岗位
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    SysRoleDTO:
      type: object
      required: [name, code]
      properties:
        name: { type: string }
        code: { type: string }
        status: { type: integer }
    SysRoleVO:
      type: object
      properties:
        id: { type: integer, format: int64 }
        name: { type: string }
        code: { type: string }
        status: { type: integer }
        createTime: { type: string, format: date-time }
        updateTime: { type: string, format: date-time }

paths:
  /api/roles:
    get:
      summary: 分页查询角色
      parameters:
        - name: page; in: query; schema: { type: integer }
        - name: size; in: query; schema: { type: integer }
      responses:
        "200": { description: OK }
    post:
      summary: 新增角色
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SysRoleDTO' }
      responses:
        "200": { description: OK }
  /api/roles/{id}:
    get:
      summary: 按 ID 查询角色
      parameters:
        - name: id; in: path; required: true; schema: { type: integer }
      responses:
        "200": { description: OK }
    put:
      summary: 更新角色
      parameters:
        - name: id; in: path; required: true; schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SysRoleDTO' }
      responses:
        "200": { description: OK }
    delete:
      summary: 删除角色
      parameters:
        - name: id; in: path; required: true; schema: { type: integer }
      responses:
        "200": { description: OK }

